apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-service
  finalizers:
    - backend.capabilities.3scale.net/finalizer
spec:
  destination:
    name: ''
    namespace: example-service
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/shpaz/3scale-gitops.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2

