apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  annotations: 
    argocd.argoproj.io/sync-wave: "1"
  name: example-service-backend
  namespace: example-service
spec:
  description: Backend for {app-name} at {app-ns}
  metrics:
    hits:
      description: Number of API hits
      friendlyName: Hits
      unit: hit
  name: example-service-backend
  privateBaseURL: 'http://example-service.example-service.svc.clusterset.local:8000'
  systemName: example-service-backend 
  providerAccountRef:
    name: menora-prod-admin-secret

