apiVersion: v1
kind: Secret
metadata:
  name: menora-prod-appauth-secret
  namespace: example-service
type: Opaque
stringData:
  admin_password: '12345678'
  password: '12345678'
  UserKey: '12345678'
